-- 처음 Supabase 테이블을 만드는 경우 이 파일을 실행하세요.
-- 이미 이전 버전의 submissions 테이블을 만든 경우에는 supabase_migration_from_old_version.sql을 실행하세요.

create table if not exists public.submissions (
    id bigint generated by default as identity primary key,
    nickname text not null,
    exam_round text not null check (exam_round in ('1회', '2회', '3회')),
    elective text not null check (elective in ('화법과작문', '언어와매체')),
    previous_korean_grade text,
    score integer not null,
    correct_count integer not null,
    total_count integer not null default 45,
    answers_json jsonb not null,
    result_json jsonb not null,
    edit_code_hash text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint submissions_one_record_per_round unique (nickname, exam_round)
);

create index if not exists submissions_round_idx on public.submissions (exam_round);
create index if not exists submissions_round_elective_idx on public.submissions (exam_round, elective);
create index if not exists submissions_nickname_idx on public.submissions (nickname);

alter table public.submissions enable row level security;

create table if not exists public.grade_cuts_by_elective (
    id bigint generated by default as identity primary key,
    exam_round text not null check (exam_round in ('1회', '2회', '3회')),
    elective text not null check (elective in ('화법과작문', '언어와매체')),
    status_message text not null default '등급컷 산출 중입니다.',
    grade_1_cut text,
    grade_2_cut text,
    grade_3_cut text,
    grade_4_cut text,
    public_note text,
    updated_at timestamptz not null default now(),
    constraint grade_cuts_by_elective_unique unique (exam_round, elective)
);

alter table public.grade_cuts_by_elective enable row level security;

insert into public.grade_cuts_by_elective (exam_round, elective, status_message)
values
    ('1회', '화법과작문', '등급컷 산출 중입니다.'),
    ('1회', '언어와매체', '등급컷 산출 중입니다.'),
    ('2회', '화법과작문', '등급컷 산출 중입니다.'),
    ('2회', '언어와매체', '등급컷 산출 중입니다.'),
    ('3회', '화법과작문', '등급컷 산출 중입니다.'),
    ('3회', '언어와매체', '등급컷 산출 중입니다.')
on conflict (exam_round, elective) do nothing;
