-- 이전 버전의 Supabase 테이블을 이미 만든 경우 Supabase SQL Editor에서 실행하세요.

alter table public.submissions
add column if not exists previous_korean_grade text;

create table if not exists public.grade_cuts_by_elective (
    id bigint generated by default as identity primary key,
    exam_round text not null check (exam_round in ('1회', '2회', '3회')),
    elective text not null check (elective in ('화법과작문', '언어와매체')),
    status_message text not null default '등급컷 산출 중입니다.',
    grade_1_cut text,
    grade_2_cut text,
    grade_3_cut text,
    grade_4_cut text,
    public_note text,
    updated_at timestamptz not null default now(),
    constraint grade_cuts_by_elective_unique unique (exam_round, elective)
);

alter table public.grade_cuts_by_elective enable row level security;

insert into public.grade_cuts_by_elective (exam_round, elective, status_message)
values
    ('1회', '화법과작문', '등급컷 산출 중입니다.'),
    ('1회', '언어와매체', '등급컷 산출 중입니다.'),
    ('2회', '화법과작문', '등급컷 산출 중입니다.'),
    ('2회', '언어와매체', '등급컷 산출 중입니다.'),
    ('3회', '화법과작문', '등급컷 산출 중입니다.'),
    ('3회', '언어와매체', '등급컷 산출 중입니다.')
on conflict (exam_round, elective) do nothing;
